#!/sbin/sh

OUTFD=$2
ZIP=$3
echo -n -e "ui_print $1 $2 $3 $4\n" > /tmp/success.txt
ui_print() {
	echo -n -e "ui_print $1\n" > /proc/self/fd/$OUTFD
	echo -n -e "ui_print\n" > /proc/self/fd/$OUTFD
}
ui_print "$1 $2 $3 $4 $5"

cd /tmp

rm -R $3/boot/KRF/*
mkdir $3/boot
mkdir $3/boot/KRF
mv boot.img $2
./unpackbootimg $2 $3/boot/KRF

echo "$3/boot/KRF/$2-zimage">$3/boot/kernel
echo "$3/boot/KRF/$2-ramdisk.gz">$3/boot/ramdisk

chmod 755 $3/boot/
chmod 755 $3/boot/KRF/
chmod 644 $3/boot/KRF/*
chmod 644 $3/boot/kernel
chmod 644 $3/boot/ramdisk

rm $2
